
version: '3.1'

services:

  backend:
    container_name: flask
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/backend
    depends_on:
      - db
    env_file: .env
    entrypoint: ["python", "main.py"]

  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file: .env
    expose:
      - 5432